# Generated by Django 6.0.4 on 2026-04-13 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_solar_salesmen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='date',
            field=models.DateField(default=(2026, 1, 1), verbose_name=models.DateField(default=datetime.date.today)),
            preserve_default=False,
        ),
    ]
