# Generated by Django 6.0.4 on 2026-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_solar_salesmen', '0002_venda_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
